### TODO update RO URI
### TODO: to be tested

PREFIX ore: <http://www.openarchives.org/ore/terms/>
PREFIX wfdesc: <http://purl.org/wf4ever/wfdesc#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX np: <http://www.nanopub.org/nschema#>

select distinct ?nanopub
where {
      <http://sandbox.wf4ever-project.org/rodl/ROs/soapdenovo-v1-5/> ore:aggregates ?nanopub .
      ?nanopub rdf:type np:Nanopublication.}
