TODO: update RO URI

PREFIX roterms: <http://purl.org/wf4ever/roterms#>
PREFIX wfdesc: <http://purl.org/wf4ever/wfdesc#>
PREFIX ore: <http://www.openarchives.org/ore/terms/>
select distinct ?study ?studyname
where { 
      <http://sandbox.wf4ever-project.org/rodl/ROs/soapdenovo-v1-5/> ore:aggregates ?workflow .
      ?workflow rdf:type wfdesc:Workflow; rdfs:seeAlso ?soap .
      #?soap a ono:data_transformation; obo:part_of ?study
      ?soap owl:sameAs [a <http://purl.obolibrary.org/obo/OBI_0200000> ; <http://purl.obolibrary.org/obo/BFO_0000050> ?study] .
      ?study rdfs:label ?studyname .
}
