### Query 7 (Demonstrate querying across the models): Find out the nanopublication statements aggregated in the RO

### Expected results

# http://w3id.org/isa/soapdenovo2/nanopub/1/
# http://w3id.org/isa/soapdenovo2/nanopub/9/
# http://w3id.org/isa/soapdenovo2/nanopub/2/
# http://w3id.org/isa/soapdenovo2/nanopub/3/
# http://w3id.org/isa/soapdenovo2/nanopub/4/
# http://w3id.org/isa/soapdenovo2/nanopub/5/
# http://w3id.org/isa/soapdenovo2/nanopub/6/
# http://w3id.org/isa/soapdenovo2/nanopub/7/
# http://w3id.org/isa/soapdenovo2/nanopub/8/

PREFIX ore: <http://www.openarchives.org/ore/terms/>
PREFIX wfdesc: <http://purl.org/wf4ever/wfdesc#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX np: <http://www.nanopub.org/nschema#>

select distinct ?nanopub
where {
      <http://sandbox.wf4ever-project.org/rodl/ROs/soapdenovo-v1-5/> ore:aggregates ?nanopub .
      ?nanopub rdf:type np:Nanopublication.}
