### Query 3: Find out the original inputs data used to execute this workflow that is aggregated in this RO

### Expected results: 

### http://w3id.org/isa/soapdenovo2/raw_data_file/17
### http://w3id.org/isa/soapdenovo2/raw_data_file/18
### http://w3id.org/isa/soapdenovo2/raw_data_file/19
### http://w3id.org/isa/soapdenovo2/raw_data_file/20
### http://w3id.org/isa/soapdenovo2/raw_data_file/21


PREFIX ore: <http://www.openarchives.org/ore/terms/>
PREFIX wfdesc: <http://purl.org/wf4ever/wfdesc#>
PREFIX roterms: <http://purl.org/wf4ever/roterms#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select distinct ?input
where { 
      <http://sandbox.wf4ever-project.org/rodl/ROs/soapdenovo-v1-5/> ore:aggregates ?workflow .
      ?workflow rdf:type wfdesc:Workflow; roterms:inputSelected ?input .}
