## Query 2: Find out the workflow(s) aggregated in the RO

### Expected results: http://sandbox.wf4ever-project.org/rodl/ROs/soapdenovo-v1-5/Workflows/Galaxy-Workflow-Workflow_constructed_from_history__reproduce_s.aureus_pipeline_.ga

PREFIX ore: <http://www.openarchives.org/ore/terms/>
PREFIX wfdesc: <http://purl.org/wf4ever/wfdesc#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select distinct ?workflow
where {
      <http://sandbox.wf4ever-project.org/rodl/ROs/soapdenovo-v1-5/> ore:aggregates ?workflow .
      ?workflow rdf:type wfdesc:Workflow .}